"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const owner_1 = __importDefault(require("./owner"));
const account_1 = __importDefault(require("./account"));
const balance_1 = __importDefault(require("./balance"));
const deposit_1 = __importDefault(require("./deposit"));
const express_1 = __importDefault(require("express"));
const withdraw_1 = __importDefault(require("./withdraw"));
const extract_1 = __importDefault(require("./extract"));
const transfer_1 = __importDefault(require("./transfer"));
const returnAccounts_1 = __importDefault(require("./returnAccounts"));
const app = (0, express_1.default)();
app.use(express_1.default.urlencoded({ extended: false }));
app.use(express_1.default.json());
app.use(owner_1.default);
app.use(account_1.default);
app.use(balance_1.default);
app.use(deposit_1.default);
app.use(withdraw_1.default);
app.use(extract_1.default);
app.use(transfer_1.default);
app.use(returnAccounts_1.default);
exports.default = app;
